In [3]:
import pandas as pd
import requests
from bs4 import BeautifulSoup

Prototyping

In [2]:
coll_url = 'https://www.collegesearch.in/engineering-colleges-india'

In [3]:
req = requests.get(coll_url)
soup = BeautifulSoup(req.content,'html5lib')

In [4]:
college = soup.find_all('h2', class_='media-heading mg-0')
soup.find_all('h2', class_='media-heading mg-0')[0]

<h2 class="media-heading mg-0">

                                                <a href="https://www.collegesearch.in/colleges/indian-institute-of-technology-iit-madras-chennai" onclick="return setTrack(1031, 'organic',1, 'search_result');" rel="noopener" title="Indian Institute of Technology, Chennai">Indian Institute of Technology, Chennai </a>
                                            </h2>

In [5]:
details=soup.find_all('dl', class_='dl-horizontal mg-0')
soup.find_all('dl', class_='dl-horizontal mg-0')[0]

<dl class="dl-horizontal mg-0">
                                            <!--Duration-->

                                                                                                <dt>Duration: </dt>
                                                    <dd>5 Years </dd>
                                                                                        <!--Fees-->
                                                                                                <dt>Total Fees: </dt>
                                                    <dd> Rs 9,00,450/-</dd>
                                                                                        <!--Affiliation-->
                                                                                                <dt>Institute Type: </dt>
                                                    <dd>Autonomous</dd>
                                                                                                                                </dl>

In [6]:
data = pd.DataFrame({'clg':college,'details':details})

In [12]:
for i in range(1,101):
    coll_url='https://www.collegesearch.in/engineering-colleges-india?page='+str(i)
    req=requests.get(coll_url)
    soup = BeautifulSoup(req.content,'html5lib')
    
    college=soup.find_all('h2', class_='media-heading mg-0')
    details=soup.find_all('dl', class_='dl-horizontal mg-0')
    
    df=pd.DataFrame({'clg':college,'details':details})
    data=data.append(df,ignore_index=True)

In [13]:
data.shape

(2180, 7)

In [14]:
data['college_name']=data['clg'].astype(str).str.split('\n',expand=True)[2].str.split('=',expand=True)[4]
data['city']=data['college_name'].astype(str).str.split(',',expand=True)[2].str.split('</a>',expand=True)[0]
data['Duration_years']=data['details'].astype(str).str.split('\n',expand=True)[4].str.split('Years',expand=True)[0].str.split('<dd>',expand=True)[1]
data['fees']=data['details'].astype(str).str.split('\n',expand=True)[7].str.split('<dd>',expand=True)[1].str.split('</dd>',expand=True)[0]
data['url']=data['clg'].astype(str).str.split('\n',expand=True)[2].str.split('=',expand=True)[1]

In [15]:
data.drop(columns=['clg','details'], axis=1, inplace=True)

In [17]:
data.drop_duplicates(keep='first',inplace=True)

In [23]:
data = data.dropna()

In [38]:
data.shape

(1016, 5)

In [30]:
data = data.reset_index(drop=True)

In [36]:
data = data.drop(['index'],axis=1)

In [37]:
data.head()

,college_name,city,Duration_years,fees,url
1,"""Indian Institute of Technology (IIT), Kanpur""...",Kanpur,4,"Rs 8,76,186/-","""https://www.collegesearch.in/colleges/indian-..."
2,"""Indian Institute of Technology (IIT), Roorkee...",Roorkee,4,"Rs 6,28,120/-","""https://www.collegesearch.in/colleges/indian-..."
3,"""Indian Institute of Technology (IIT), Kharagp...",Kharagpur,4,"Rs 10,65,980/-","""https://www.collegesearch.in/colleges/indian-..."
4,"""Indian Institute of Technology, Delhi"">Indian...",Delhi,4,"Rs 9,95,600/-","""https://www.collegesearch.in/colleges/indian-..."
5,"""Indian Institute of Technology Bombay, Mumbai...",Mumbai,5,"Rs 11,40,000/-","""https://www.collegesearch.in/colleges/indian-..."

In [39]:
data.to_excel('college_data.xlsx')

In [4]:
data = pd.read_excel('./college_data.xlsx')

In [9]:
Delhi = data[data['city'] == ' Delhi ']
Mumbai = data[data['city'] == ' Mumbai ']
Kolkata = data[data['city'] == ' Kolkata ']
Chennai = data[data['city'] == ' Chennai ']

In [10]:
Delhi

,Unnamed: 0,college_name,city,Duration_years,fees,url
3,4,"""Indian Institute of Technology, Delhi"">Indian...",Delhi,4,"Rs 9,95,600/-","""https://www.collegesearch.in/colleges/indian-..."
14,15,"""Delhi Technological University (DTU), Delhi"">...",Delhi,4,"Rs 9,31,400/-","""https://www.collegesearch.in/university/delhi..."
51,52,"""Indraprastha Institute of Information Technol...",Delhi,4,"Rs 16,00,000/-","""https://www.collegesearch.in/colleges/indrapr..."
62,63,"""Netaji Subhas University of Technology - NSIT...",Delhi,4,"Rs 8,44,000/-","""https://www.collegesearch.in/colleges/netaji-..."
65,66,"""Indira Gandhi Delhi Technical University for ...",Delhi,4,"Rs 3,00,000/-","""https://www.collegesearch.in/university/indir..."
69,70,"""National Institute of Technology (NIT), Delhi...",Delhi,4,"Rs 6,61,200/-","""https://www.collegesearch.in/colleges/nationa..."
73,74,"""Faculty of Engineering &amp; Technology - Jam...",Delhi,4,"Rs 85,780/-","""https://www.collegesearch.in/colleges/faculty..."
109,110,"""Ambedkar Institute of Advanced Communication ...",Delhi,4,"Rs 1,60,000/-","""https://www.collegesearch.in/colleges/ambedka..."
126,127,"""Delhi Engineering College, Delhi"">Delhi Engin...",Delhi,4,"Rs 94,000/-","""https://www.collegesearch.in/colleges/delhi-e..."
166,167,"""Maharaja Surajmal Institute of Technology (MS...",Delhi,4,"Rs 3,60,248/-","""https://www.collegesearch.in/colleges/maharaj..."
223,224,"""Maharaja Agrasen Institute of Technology (MAI...",Delhi,4,"Rs 9,26,400/-","""https://www.collegesearch.in/colleges/maharaj..."
289,290,"""Bharati Vidyapeeth’s College of Engineering, ...",Delhi,4,"Rs 4,47,800/-","""https://www.collegesearch.in/colleges/bharati..."
329,330,"""BM Group of Institutions (BMGI), Delhi"">BM Gr...",Delhi,4,"Rs 3,20,000/-","""https://www.collegesearch.in/colleges/bm-grou..."
398,399,"""Guru Tegh Bahadur Institute of Technology (GT...",Delhi,4,"Rs 4,26,000/-","""https://www.collegesearch.in/colleges/guru-te..."
418,419,"""School of Engineering &amp; Technology - IGNO...",Delhi,4,"Rs 20,000/-","""https://www.collegesearch.in/colleges/school-..."
652,653,"""Ganga Group of Institutions, Delhi"">Ganga Gro...",Delhi,4,"Rs 3,12,000/-","""https://www.collegesearch.in/colleges/ganga-g..."
656,657,"""Amity School of Engineering and Technology (A...",Delhi,4,"Rs 2,12,000/-","""https://www.collegesearch.in/university/amity..."
657,658,"""HMR Institute of Technology and Management, D...",Delhi,4,"Rs 3,78,000/-","""https://www.collegesearch.in/colleges/hmr-ins..."
667,668,"""Indraprastha Institute of Technology and Mana...",Delhi,4,"Rs 4,55,000/-","""https://www.collegesearch.in/colleges/institu..."
695,696,"""Shyama Prasad Mukherji College for Women, Del...",Delhi,4,"Rs 20,800/-","""https://www.collegesearch.in/colleges/shyama-..."
834,835,"""Guru Premsukh Memorial College of Engineering...",Delhi,4,"Rs 3,17,000/-","""https://www.collegesearch.in/colleges/guru-pr..."
943,944,"""Dr Akhilesh Das Gupta Institute of Technology...",Delhi,4,"Rs 4,20,000/-","""https://www.collegesearch.in/colleges/Dr-Akhi..."

In [6]:
Kolkata

,Unnamed: 0,college_name,city,Duration_years,fees,url
63,64,"""Government College of Engineering &amp; Ceram...",Kolkata,4,"Rs 48,000/-","""https://www.collegesearch.in/colleges/governm..."
98,99,"""Kalyani Government Engineering College (KGEC)...",Kolkata,4,"Rs 40,620/-","""https://www.collegesearch.in/colleges/kalyani..."
269,270,"""Haldia Institute of Technology, Kolkata"">Hald...",Kolkata,4,"Rs 4,26,700/-","""https://www.collegesearch.in/colleges/haldia-..."
270,271,"""Institute of Engineering and Management (IEM)...",Kolkata,4,"Rs 3,76,000/-","""https://www.collegesearch.in/colleges/institu..."
288,289,"""RCC Institute of Information Technology - (RC...",Kolkata,4,"Rs 3,69,300/-","""https://www.collegesearch.in/colleges/rcc-ins..."
293,294,"""Bengal Institute of Technology, Kolkata"">Beng...",Kolkata,4,"Rs 2,88,000/-","""https://www.collegesearch.in/colleges/bengal-..."
304,305,"""Swami Vivekananda Institute of Science and Te...",Kolkata,4,"Rs 5,60,000/-","""https://www.collegesearch.in/colleges/swami-v..."
391,392,"""MCKV Institute of Engineering, Kolkata"">MCKV ...",Kolkata,4,"Rs 3,61,200/-","""https://www.collegesearch.in/colleges/mckv-in..."
402,403,"""Brainware University, Kolkata"">Brainware Univ...",Kolkata,4,"Rs 4,48,000/-","""https://www.collegesearch.in/university/brain..."
406,407,"""Pailan College of Management &amp; Technology...",Kolkata,4,"Rs 3,17,200/-","""https://www.collegesearch.in/colleges/pailan-..."
411,412,"""Future Institute of Engineering and Managemen...",Kolkata,4,"Rs 3,32,000/-","""https://www.collegesearch.in/colleges/future-..."
473,474,"""Heritage Institute of Technology, Kolkata"">He...",Kolkata,4,"Rs 4,27,000/-","""https://www.collegesearch.in/colleges/heritag..."
474,475,"""Narula Institute of Technology, Kolkata"">Naru...",Kolkata,4,"Rs 4,07,900/-","""https://www.collegesearch.in/colleges/narula-..."
496,497,"""BP Poddar Institute of Management &amp; Techn...",Kolkata,4,"Rs 3,57,000/-","""https://www.collegesearch.in/colleges/bp-podd..."
502,503,"""JIS College of Engineering, Kolkata"">JIS Coll...",Kolkata,4,"Rs 4,06,400/-","""https://www.collegesearch.in/colleges/jis-col..."
523,524,"""Calcutta Institute of Engineering and Managem...",Kolkata,4,"Rs 3,57,000/-","""https://www.collegesearch.in/colleges/calcutt..."
668,669,"""St Thomas’ College of Engineering &amp; Techn...",Kolkata,4,"Rs 3,57,000/-","""https://www.collegesearch.in/colleges/st-thom..."
791,792,"""Techno India University, Kolkata"">Techno Indi...",Kolkata,5,"Rs 9,02,000/-","""https://www.collegesearch.in/university/techn..."
825,826,"""Supreme knowledge Foundation Group of Institu...",Kolkata,4,"Rs 2,80,000/-","""https://www.collegesearch.in/colleges/supreme..."
840,841,"""OmDayal College of Engineering &amp; Architec...",Kolkata,4,"Rs 3,28,300/-","""https://www.collegesearch.in/colleges/omdayal..."
963,964,"""Netaji Subhash Engineering College, Kolkata"">...",Kolkata,4,"Rs 5,50,000/-","""https://www.collegesearch.in/colleges/Netaji_..."

In [27]:
def all_cap():
    capitals = [    "Itanagar",    "Dispur",    "Patna",    "Raipur",    "Panaji",    "Gandhinagar",    "Chandigarh",    "Shimla",    "Srinagar",    "Ranchi",    "Bengaluru",    "Thiruvananthapuram",    "Bhopal",    "Mumbai",    "Imphal",    "Shillong",    "Aizawl",    "Kohima",    "Bhubaneswar",    "Chandigarh",    "Jaipur",    "Gangtok",    "Chennai",    "Hyderabad",    "Agartala",    "Lucknow",    "Dehradun",    "Kolkata",    "Delhi"]
    for elem in capitals:
        dat = data[data['city'] == ' '+elem+' ']
        print(dat['college_name'])

In [36]:
def all_cities():
    print(data['college_name'])

In [35]:
def college_by_city(inp):
    if inp==1:
        print(Delhi['college_name'],Mumbai['college_name'],Kolkata['college_name'],Chennai['college_name'])
    if inp==2:
        all_cap()
    if inp==3:
        all_cities()
    else:
        return "Invalid Input"

In [37]:
n = int(input("Enter 1. for Metro Cities 2. for all Capitals 3. for all colleges/cities"))
college_by_city(n)

0       "Indian Institute of Technology (IIT), Kanpur"...
1       "Indian Institute of Technology (IIT), Roorkee...
2       "Indian Institute of Technology (IIT), Kharagp...
3       "Indian Institute of Technology, Delhi">Indian...
4       "Indian Institute of Technology Bombay, Mumbai...
                              ...
1011    "Vidhyapeeth Institute of Science and Technolo...
1012    "NRI Institute of Research &amp; Technology, B...
1013    "SGBM Institute of Technology &amp; Science, J...
1014    "Babu Banarsi Das National Institute of Techno...
1015    "Rishi Chadha Vishvas Girls Institute of Techn...
Name: college_name, Length: 1016, dtype: object